s=set()


n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))
n=input("enter the number:") 
s.add(int(n))

print(s)
